name = "utahchurches"
main = "src/index.tsx"
compatibility_date = "2025-01-19"
assets = { directory = "./public" }

# Enable Workers Logs
[observability]
enabled = true

# D1 Database Configuration
# Create your D1 databases using:
# wrangler d1 create your-database-name
# Then update the database_id values below with the output from those commands

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "your-database-id-here"
preview_database_id = "your-preview-database-id-here"

# R2 Bucket Configuration
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "your-bucket-name"

[vars]
# Add your non-sensitive configuration here
# For production, set the following secrets using wrangler:
# wrangler secret put GOOGLE_MAPS_API_KEY
# wrangler secret put GOOGLE_SSR_KEY
# wrangler secret put BETTER_AUTH_SECRET
# wrangler secret put BETTER_AUTH_URL
# wrangler secret put GOOGLE_CLIENT_ID
# wrangler secret put GOOGLE_CLIENT_SECRET